import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;

/**
 *
 * @author Lukas Reining
 */
public class DecodePanel extends javax.swing.JPanel {

    private GUI gui;
    private Huffman huffman;

    /**
     * Creates new form DecodePanel
     */
    public DecodePanel(GUI gui) {
        initComponents();
        this.gui = gui;
        huffman = new Huffman();
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaCoded = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDecoded = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonMainMenu = new javax.swing.JButton();
        buttonLoad = new javax.swing.JButton();
        labelPath = new javax.swing.JLabel();

        textAreaCoded.setColumns(20);
        textAreaCoded.setEditable(false);
        textAreaCoded.setLineWrap(true);
        textAreaCoded.setRows(5);
        textAreaCoded.setWrapStyleWord(true);
        textAreaCoded.setName("taCoded"); // NOI18N
        jScrollPane1.setViewportView(textAreaCoded);

        textAreaDecoded.setColumns(20);
        textAreaDecoded.setEditable(false);
        textAreaDecoded.setLineWrap(true);
        textAreaDecoded.setRows(5);
        textAreaDecoded.setWrapStyleWord(true);
        textAreaDecoded.setName("taDecoded"); // NOI18N
        jScrollPane2.setViewportView(textAreaDecoded);
        textAreaDecoded.getAccessibleContext().setAccessibleName("");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Decodiert:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Codiert:");

        buttonMainMenu.setText("Zur\u00fcck");
        buttonMainMenu.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonMainMenuActionPerformed(evt);
                }
            });

        buttonLoad.setText("Lade Datei");
        buttonLoad.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonLoadActionPerformed(evt);
                }
            });

        labelPath.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelPath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPath.setText("Bitte Datei ausw\u00e4hlen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonMainMenu)
                        .addGap(18, 18, 18)
                        .addComponent(labelPath, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonLoad)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMainMenu)
                    .addComponent(buttonLoad)
                    .addComponent(labelPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainMenuActionPerformed
        textAreaCoded.setText("");
        textAreaDecoded.setText("");
        gui.showMainMenu();
    }//GEN-LAST:event_buttonMainMenuActionPerformed

    private void buttonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Huffmandatei laden");
        FileFilter filter = new FileNameExtensionFilter("Huffmandatei", "huff");
        fileChooser.removeChoosableFileFilter(fileChooser.getAcceptAllFileFilter()); 
        fileChooser.setFileFilter(filter);
        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            labelPath.setText(fileToSave.getAbsolutePath());
            Huffmancode huffmancode = Filesaver.loadHuffmanFromFile(fileToSave.getAbsolutePath());
            if(huffmancode != null){
                textAreaCoded.setText(huffmancode.getCode());
                textAreaDecoded.setText(huffman.decompress(huffmancode));
            }else{
                JOptionPane.showMessageDialog(this,"Bitte eine g\u00fcltige Huffmandatei ausw\u00e4hlen.","Datei ung\u00fcltig",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonLoadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLoad;
    private javax.swing.JButton buttonMainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelPath;
    private javax.swing.JTextArea textAreaCoded;
    private javax.swing.JTextArea textAreaDecoded;
    // End of variables declaration//GEN-END:variables
}
