import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.File;

/**
 *
 * @author Lukas Reining
 */
public class EncodePanel extends javax.swing.JPanel {

    private GUI gui;
    private Huffman huffman;
    private Huffmancode huffmancode;

    /**
     * Creates new form EncodePanel
     */
    public EncodePanel(GUI gui) {
        initComponents();
        this.gui = gui;
        huffman = new Huffman();
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonMainMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaKlartext = new javax.swing.JTextArea();
        buttonCodieren = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaCoded = new javax.swing.JTextArea();
        buttonSave = new javax.swing.JButton();

        buttonMainMenu.setText("Zur\u00fcck");
        buttonMainMenu.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonMainMenuActionPerformed(evt);
                }
            });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Klartext:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Codierung:");

        textAreaKlartext.setColumns(20);
        textAreaKlartext.setLineWrap(true);
        textAreaKlartext.setRows(5);
        textAreaKlartext.setWrapStyleWord(true);
        textAreaKlartext.setName("taCoded"); // NOI18N
        jScrollPane1.setViewportView(textAreaKlartext);

        buttonCodieren.setText("Codieren");
        buttonCodieren.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonCodierenActionPerformed(evt);
                }
            });

        textAreaCoded.setColumns(20);
        textAreaCoded.setEditable(false);
        textAreaCoded.setLineWrap(true);
        textAreaCoded.setRows(5);
        textAreaCoded.setWrapStyleWord(true);
        textAreaCoded.setName("taDecoded"); // NOI18N
        jScrollPane2.setViewportView(textAreaCoded);

        buttonSave.setText("Speichern");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttonSaveActionPerformed(evt);
                }
            });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMainMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(buttonCodieren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonMainMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCodieren, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCodierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCodierenActionPerformed
        huffmancode = huffman.compress(textAreaKlartext.getText());
        textAreaCoded.setText(huffmancode.getCode());
    }//GEN-LAST:event_buttonCodierenActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        if(huffmancode != null){
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Speichern");
            int userSelection = fileChooser.showSaveDialog(this);
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                Filesaver.saveHuffmanToFile(huffmancode,fileToSave.getAbsolutePath());
            }
        }else{
            JOptionPane.showMessageDialog(this,"Bitte einen Text codieren, bevor eine Datei gespeichert werden kann.","Keine Codierung",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainMenuActionPerformed
        huffmancode = null;
        textAreaKlartext.setText("");
        textAreaCoded.setText("");
        gui.showMainMenu();
    }//GEN-LAST:event_buttonMainMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCodieren;
    private javax.swing.JButton buttonMainMenu;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaCoded;
    private javax.swing.JTextArea textAreaKlartext;
    // End of variables declaration//GEN-END:variables
}
